# Generated by Django 4.1.7 on 2023-02-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name', 'updated_date'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'ordering': ['contact__name', 'updated_date'], 'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
    ]
