# Generated by Django 4.1.7 on 2023-03-24 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_contact_options_alter_phonenumber_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name', '-updated_date'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'ordering': ['contact__name', '-updated_date'], 'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользватель'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phone_numbers', to='app.contact', verbose_name='Контакт'),
        ),
    ]
